services:
  mongodb:
    image: mongo:6
    command: --bind_ip 0.0.0.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/smartstock
    networks:
      - app-network

  ai-service:
    build: ./ai-service
    container_name: python-ai
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/smartstock
    networks:
      - app-network

  frontend:
    build: ./SmartStockUI
    container_name: react-ui
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - ai-service
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
